sudo: required

language: python

python:
  - "3.6"

env:
  global:
    - DB_USER=postgres
    - DB_NAME=likeafalcon
    - DB_PASSWORD=mysecretpassword
    - DB_PORT=15432
    - STREAM_URI=nats://localhost:4222

services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get install docker-ce
  - pip install tox codecov
  - docker run -d --name streams -p 4222:4222 nats-streaming:0.6.0
  - docker run -d --name postgres -e POSTGRES_DB=$DB_NAME -e POSTGRES_USER=$DB_USER -e POSTGRES_PASSWORD=$DB_PASSWORD -p $DB_PORT:5432 postgres:10.0
script:
  - tox
after_success:
  - docker rm -f streams
  - docker rm -f postgres
  - codecov
