version: '3.3'

services:
  streams:
    image: nats-streaming:0.6.0
  db:
    image: postgres:10.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=postgres
      - POSTGRES_DB=likeafalcon
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_PASSWORD=mysecretpassword
      - DB_USER=postgres
      - DB_NAME=likeafalcon
      - DB_HOST=db
      - STREAM_URI=nats://streams:4222
    depends_on:
      - db
      - streams
